if SHIELD_IRIS_CUSTOM_LEFT

config ZMK_KEYBOARD_NAME
    default "Iris Custom"

config ZMK_SPLIT_ROLE_CENTRAL
    default y

endif

if SHIELD_IRIS_CUSTOM_LEFT || SHIELD_IRIS_CUSTOM_RIGHT

config ZMK_SPLIT
    default y

endif
